start:
  shell-commands:
    - clear 
  messages:
    - "Hello Everyone, Welcome to Udocker Wrapper :)"
    - "_____________________________________________"
steps:
  - question: "What type plataform/os are you using?"
    key: "question-1"
    observation: "'Linux' can be any distribuitions"
    options:
      list:
        - name: "Linux/Distros"
          key: "distributions"

        - name: "Android/Termux"
          key: "termux"

  - question: "Where do you want to install project folder?"
    key: "question-2"
    observation: "These folders will use your plataform to create relatives directories"
    python-commands:
      - "if not os.environ.get('HOME'):\n\traise ValueError('Didnt possible to find $HOME environment variable.')"
    globals:
      variables:
        - key: "PATH-TO-UDOCKER"
          values:
            - "Now put these lines into your source file if you want to use udocker on restart"
        - key: "SOURCE-FILE"
          values: 
            - "source $HOME/[.bashrc or .zshrc, .config/fish/config.fish]"
    options:
      dependsOn: "question-1"
      list:
        - name: "$HOME/.udocker"
          key: "home"
          values: 
            - key: "distributions"
              shell-commands:
                - echo "HOME"

            - key: "termux"
              shell-commands:
                - echo '
                    $PATH-TO-UDOCKER\n
                    \t> export PATH="$PATH:$HOME/udocker/udocker/udocker"\n
                    \t> $SOURCE-FILE'
        - name: "/opt/udocker"
          key: "opt"
          values: 
            - key: "distributions"
              shell-commands:
                - echo "OPT"

            - key: "termux"
              shell-commands:
                - echo "OPT"

        - name: "/usr/lib/python{version}/site-packages/udocker"
          key: "usr-lib"
          values: 
            - key: "distributions"
              shell-commands:
                - echo "USR-LIB"

            - key: "termux"
              shell-commands:
                - echo "]USR-LIB"
end:
  messages:
    - "Everything was ok."
    - "To use, just type: udocker [commands]"
    - "\nToo now you can delete this installation folder."
    - "Just type: rm -rf ../udocker-wrapper\n"
